export { ColorIconBase, type ColorIconProps } from './ColorIconBase'
export { IconBase, type IconProps } from './IconBase'
export { ColorIconBaseSmall } from './ColorIconBaseSmall'
export { isThemeColor } from './isThemeColor'
export { getFirstLetterCapitalized } from './getFirstLetterCapitalized'
